
# Syntax highlighting
markdown:            kramdown
highlighter:         pygments

# Permalinks
#permalink:           /:title
permalink: pretty
#relative_permalinks: true

# Setup
timezone:            Rome # eg. Asia/Kathmandu
locale:              it # eg. en_us
name:				         unit
title:               unit srl
tagline:             'Mobile Web App Development Experts'
description:         'Mobile Web App Development Experts'
url:                 unitsystems.eu
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                '/assets/images/logo.png' #[best 300px X 300px]

author:
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
